import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Coloração Profissional VLOSS',
    brand: 'VLOSS',
    category: 'COLORAÇÃO',
    description: 'Cobertura de 100% dos fios brancos com cores vibrantes, duradouras e brilho intenso. Escolha sua cor.',
    price: 28.50,
    imageUrl: 'https://picsum.photos/seed/haircolor1/600/600',
    variants: [
      { id: 1001, name: '1.0 Preto Azulado', isOutOfStock: false },
      { id: 1002, name: '3.0 Castanho Escuro', isOutOfStock: false },
      { id: 1003, name: '4.0 Castanho Médio', isOutOfStock: false },
      { id: 1004, name: '5.0 Castanho Claro', isOutOfStock: false },
      { id: 1005, name: '6.0 Louro Escuro', isOutOfStock: false },
      { id: 1006, name: '7.4 Louro Cobre', isOutOfStock: true },
    ],
  },
  {
    id: 2,
    name: 'Máscara de Hidratação Profunda',
    brand: 'CANVENSE',
    category: 'Tratamentos',
    description: 'Reparação intensiva para cabelos secos e danificados. Devolve a maciez e o brilho.',
    price: 79.90,
    imageUrl: 'https://picsum.photos/seed/hairmask/600/600',
  },
  {
    id: 3,
    name: 'Pó Descolorante Rápido 9 Tons',
    brand: 'VLOSS',
    category: 'Descoloração',
    description: 'Abre até 9 tons de forma segura e eficaz. Fórmula Dust-Free com ação anti-amarelamento.',
    price: 119.90,
    imageUrl: 'https://picsum.photos/seed/bleach/600/600',
  },
  {
    id: 4,
    name: 'Tonalizante Sem Amônia',
    brand: 'VIA CHARM',
    category: 'COLORAÇÃO',
    description: 'Banho de brilho que realça a cor dos cabelos, com fórmula suave que trata enquanto colore. Escolha sua cor.',
    price: 35.00,
    imageUrl: 'https://picsum.photos/seed/haircolor2/600/600',
    variants: [
        { id: 4001, name: 'Castanho Iluminado' },
        { id: 4002, name: 'Chocolate' },
        { id: 4003, name: 'Mel Dourado' },
        { id: 4004, name: 'Marsala' },
    ]
  },
  {
    id: 5,
    name: 'Sérum Reparador de Pontas',
    brand: 'CANVENSE',
    category: 'Tratamentos',
    description: 'Sela as cutículas, controla o frizz e protege contra o calor do secador e chapinha. Toque sedoso.',
    price: 49.90,
    imageUrl: 'https://picsum.photos/seed/serum/600/600',
  },
  {
    id: 6,
    name: 'Kit Cronograma Capilar Completo',
    brand: 'HOKA',
    category: 'Tratamentos',
    description: 'Conjunto com 3 máscaras (Hidratação, Nutrição e Reconstrução) para um tratamento completo.',
    price: 219.90,
    imageUrl: 'https://picsum.photos/seed/kit/600/600',
  },
  {
    id: 7,
    name: 'Água Oxigenada Cremosa 30 Volumes',
    brand: 'VLOSS',
    category: 'Descoloração',
    description: 'Emulsão reveladora estabilizada, ideal para processos de coloração e descoloração.',
    price: 15.00,
    imageUrl: 'https://picsum.photos/seed/developer/600/600',
  },
  {
    id: 8,
    name: 'Ampola de Reconstrução Imediata',
    brand: 'VIA CHARM',
    category: 'Tratamentos',
    description: 'Dose concentrada de queratina e aminoácidos para cabelos quimicamente tratados.',
    price: 19.90,
    imageUrl: 'https://picsum.photos/seed/ampoule/600/600',
  },
  {
    id: 9,
    name: 'Progressiva Orgânica Sem Formol',
    brand: 'LESCOR',
    category: 'ALISAMENTOS',
    description: 'Alisamento capilar de alta performance que promove efeito liso natural, com brilho e sem frizz. Fórmula orgânica e sem formol.',
    price: 250.00,
    imageUrl: 'https://picsum.photos/seed/alisamento/600/600',
  },
  {
    id: 10,
    name: 'Pomada Modeladora Efeito Matte',
    brand: 'BLACKPOOL',
    category: 'Finalizadores',
    description: 'Fixação forte com acabamento sem brilho. Ideal para penteados modernos e estruturados.',
    price: 42.00,
    imageUrl: 'https://picsum.photos/seed/pomade/600/600',
  },
  {
    id: 11,
    name: 'Óleo de Argan Imperial',
    brand: 'HOKA',
    category: 'Tratamentos',
    description: 'Tratamento luxuoso com óleo de argan puro. Nutrição intensa, brilho espelhado e controle do frizz.',
    price: 159.90,
    imageUrl: 'https://picsum.photos/seed/arganoil/600/600',
  },
  {
    id: 12,
    name: 'Spray de Brilho Intenso',
    brand: 'VLOSS',
    category: 'Finalizadores',
    description: 'Finalizador em spray que proporciona um brilho luminoso e instantâneo aos fios.',
    price: 55.00,
    imageUrl: 'https://picsum.photos/seed/shine/600/600',
  },
  {
    id: 13,
    name: 'Leave-in Protetor Térmico',
    brand: 'VIA CHARM',
    category: 'Finalizadores',
    description: 'Protege os cabelos do calor de ferramentas térmicas, desembaraça e hidrata.',
    price: 38.50,
    imageUrl: 'https://picsum.photos/seed/leavein/600/600',
  },
  {
    id: 14,
    name: 'Kit Manutenção Pós-Química',
    brand: 'HOKA',
    category: 'HOME CARE',
    description: 'Kit com shampoo e condicionador para cuidar dos cabelos em casa, prolongando o efeito do tratamento de salão.',
    price: 129.90,
    imageUrl: 'https://picsum.photos/seed/homecare/600/600',
  },
];